config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'homes/top'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "homes#top"

  resources :post_images, only: [:new, :create, :show, :edit, :index, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :index, :update] do
    resources :relationships, only: [:create, :destroy]
  end
  get "/users/:id/index" => "users#withdraw", as: "withdraw"
  resources :categories, only: [:index, :show, :create, :edit, :update]
  get 'items/search'


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :post_images, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_one_attached :profile_image
  has_many :favorites, dependent: :destroy

  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :active_relationships, source: :followed

  # フォローされている側のユーザー(passive relationship)
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :categories
  enum gender: { man: 0, woman: 1}

  def get_profile_image(size)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpeg')
      profile_image.attach(io: File.open(file_path), filename: 'no_image.jpeg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize: size).processed
  end

  def age
    today = Date.today # 2014/3/27

    age = today.year - birth_date.year
    if today.month < birth_date.month or (today.month == birth_date.month and today.day < birth_date.day)
      age -= 1 # まだ誕生日を迎えていない
    end

    age
  end

  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  # ユーザーをアンフォロー
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # 相手をフォローしていればtrueを返す
  def following?(other_user)
    active_relationships.find_by(followed_id: other_user.id)
  end

  # 友達（互いにフォローしている）をデータベースから取得
  def matchers
    followings & followers
  end

  # 相手と友達になっていればtrueを返す
  def matchers?(other_user)
    active_relationships.find_by(followed_id: other_user.id) && passive_relationships.find_by(follower_id: other_user.id)
  end

  # 自分はフォローしていない&相手からフォローされていればtrueを返す
  def follow_request?(user, other_user)
    !user.matchers?(other_user) && other_user.following?(user)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @mates = current_user.matchers
    users_id = current_user.followings.pluck(:id)
    pp users_id
    users_id.push(current_user.id)
    pp users_id
    @users = User.where.not(id: users_id)
    @user = current_user
  end

  def show
    @user = User.find(params[:id])
    @post_images = @user.post_images

  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    if @user.save
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
    render :edit
    end
  end

  def edit
    @user = current_user
    if current_user.id != @user.id
    redirect_to users_path
    end

  end

  def withdraw
    @user = current_user

  end

  def destroy
    user = User.find(params[:id])
    user.update(is_deleted: true)
    flash[:success] = "アカウントを削除しました"
    redirect_to root_path

  end


  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :gender, :birth_date)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<div class="row" id="main_background">
<div class="container">
  <div class="row">
  <div class="mx-auto col-12 col-sm-10 col-lg-8 col-xl-6">


　<h3 class="font-weight-bold">
　 Edit my profile</h3>

<%= form_with model: @user, local:true do |f| %>
<div class= "form-group">
 <label for="inputName">Name</label><br>
 <%= f.text_field :name, autofocus: true, id:"inputName" %><br>
 </div>
 <div class= "form-group">
 <label for="inputImage">Profile image</label><br>
 <%= f.file_field :profile_image, placeholder: "Image", accept: "image/*" %><br>
 </div>

  <div class="field">
  <%= f.label :birthday %><br>
  <%= f.date_select :birth_date, use_month_numbers: true,start_year: 1930, end_year: (Time.now.year - 10), default: Date.new(1989, 1, 1) %>
  </div>

  <div class= "form-group">
    <%= f.label :gender %><br />
    <%= f.label :man  %>
    <%= f.radio_button :gender, :man %>
    <%= f.label :woman  %>
    <%= f.radio_button :gender, :woman %>
  </div>
  <div class= "form-group">
   <%= f.submit "Save", class: "btn btn-outline-success mt-3 mr-5" %>

  </div>
  <% end %>



   <%= link_to "退会する", withdraw_path(@user), class: "btn btn-outline-danger mt-3 mb-5" %>

　  </div>
　</div>
</div>

app/views/users/index.html.erb
<div class="row" id="main_background">
<div class="container">
  <div class="row">
   <div class="col-4 border rounded border-info h-50 mt-5 mb-5" id="color">
  <%= render 'post_images/list', post_image: @post_image, user: @user %>
  </div>

   <div class="col-8">
    <h3 class="font-weight-bold ml-5 mt-5"><i class="fas fa-users text-info"></i> Roommate list</h3>
    <table class="table table-hover table-inverse ml-5">
      <thead>
       <tr>
        <th>image</th>
        <th>name</th>
        <th colspan="1"></th>
       </tr>
      </thead>

      <tbody>

        <% @mates.each do |user| %>

        <tr>
          <td><%= link_to user_path(user.id) do%>
           <%= image_tag user.get_profile_image("50x50") %>
           <% end %>
                <% if user.id == current_user.id %>
                <% end %></td>
          <td>
           <%= link_to user.name, user_path(user.id) %></td>

        </tr>
            <% end %>
      </tbody>
    </table>

    <h3 class="font-weight-bold ml-5"><i class="fas fa-users text-warning"></i> User list</h3>
      <table class="table table-hover table-inverse ml-5">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th colspan="1"></th>
          </tr>
        </thead>

      <tbody>
        <%@users.each do |user| %>
        <% unless current_user.id == user.id %>

          <tr>
            <td><%= image_tag user.get_profile_image("50x50") %>
                <% if user.id == current_user.id %>
                <% end %></td>
            <td><%= link_to user.name, user_path(user.id) %></td>
              <% if user.follow_request?(current_user, user) %>
                    <p><i class="fas fa-star"></i></p>
                  <% end %>

          </tr>
        <% end %>
        <% end %>
      </tbody>
      </table>
     </div>
   </div>
</div>

app/views/users/show.html.erb
<div class="row" id="main_background">
  <div class="container">
    <div class="row">
      <div class="col-4 border rounded border-info mb-5 h-50 mt-5" id="color">
        <%= render 'post_images/list', post_image: @post_image, user: @user %>

        <% if @user.follow_request?(current_user, @user) %>
          <div class="form-group">
            <div class="schedule-item">
              <div class="schedule-item-header text-left">
                <p class="bold"><i class="fas fa-star"></i>You have follow request<i class="fas fa-star"></i></p>
              </div>
              <div class="schedule-item-body text-left">
                <p><%= @user.name %> requests you to be mate</p>
              </div>
            </div>
          </div>
        <% end %>
        <% if current_user.matchers?(@user) %>
          <div class="form-group">
            <div class="schedule-item">
              <div class="schedule-item-header text-left">
                <p class="bold font-weight-bold ml-5"><%= @user.name %> is your mate</p>
              </div>
            </div>
          </div>
          <% end %>

        <% if current_user.id == @user.id %>

        <% else %>
          <% unless current_user.following?(@user) %>
            <div class="actions">
              <%= link_to 'Request to be mate', user_relationships_path(@user.id), method: :post, class:"btn btn-outline-success mt-3 mr-5 ml-5 mb-3" %>
            </div>
          <% else %>
            <div class="actions">
              <%= link_to 'Cancel to your request', user_relationship_path(@user.id), method: :delete, class:"btn btn-outline-danger mt-3 mr-5 mb-3 ml-5" %>
            </div>
          <% end %>
        <% end %>

      </div>

      <div class="col-8">
        <h3 class="font-weight-bold ml-5 mt-5"><i class="fas fa-solid fa-star text-success"></i> Posts</h3><br>
        <div class="row">
          <% @post_images.each do |post_image| %>
            <div class= "form-group mb-5 mr-5 ml-5 review-group">
              <%= link_to post_image_path(post_image.id) do %>
                <%= image_tag post_image.image.present? ? post_image.image : "", class: "list_image" %>
              <% end %>
              <p>Title:  <%= post_image.title %></p>
              <p>Memo: <%= simple_format(post_image.memo) %></p>
              <p>Category：<%= post_image.category.name %></p>
              <div id="star"></div>
              <div id="star-rate<%= post_image.id%>"></div>
              <script>
                $('#star-rate<%= post_image.id%>').raty({
                  size      : 36,
                  starOff   : '<%= asset_path('star-off.png') %>',
                  starOn    : '<%= asset_path('star-on.png') %>',
                  half      : false,
                  readOnly: true,
                  <%# if post_image.review.blank? %>
                  //score: 0
                  <%# else %>
                  //score: <%#= post_image.review %>
                  <%# end %>
                  score: <%= post_image.review.blank? ? 0 : post_image.review %>
                });
              </script>
              <p>Date: <%= post_image.created_at.strftime('%Y/%m/%d') %></p>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>

app/views/users/withdraw.html.erb
<div class="row" id="main_background">
  <div class="container">
    <div class="row">
  	  <div class="mx-auto text-center mt-5 ml-5">
	      <div class = "body" style>

			    <h3>本当に退会しますか？</h3>

			      <div class = "withdrawal_text">退会すると、<br>
				      これまでの投稿などが閲覧できなくなります。<br>
				      退会する場合は、「退会する」をクリックしてください。
			      </div>

						<%= link_to "退会しない", users_path(@user), class: "btn btn-outline-primary mt-5 ml-I 4 mr-5 mb-5"%>&ensp;
						<%= link_to "退会する", destroy_session_path(@user), method: :patch, data: {confirm: "本当に退会してもよろしいですか？"}, class: "btn btn-outline-danger mt-5 ml-3 mb-5" %>

					</div>
				</div>
		</div>
	</div>
</div>