config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'homes/top'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "homes#top"

  resources :post_images, only: [:new, :create, :show, :edit, :index, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :index, :update] do
    resources :relationships, only: [:create, :destroy]
  end
  get "/users/:id/index" => "users#withdraw", as: "withdraw"
  resources :categories, only: [:index, :show, :create, :edit, :update]
  get 'items/search'


end

app/models/category.rb
class Category < ApplicationRecord

  has_many :post_images, dependent: :destroy
  validates :name, presence: true
  belongs_to :user

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpeg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpeg', content_type: 'image/jpeg')
    end
    image
  end

  def get_profile_image(size)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize: size).processed
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
def index
    @categories = Category.all
    @category = Category.new
    @user = current_user

end

def create
    category = Category.new(category_params)
    category.user = current_user
    category.save
    redirect_to categories_path
end

def show
  @category = Category.find(params[:id])
  @post_images = @category.post_images
  @user = current_user

end

def edit
    @category = Category.find(params[:id])

end

def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      redirect_to categories_path
      flash[:success] = "編集に成功しました"
    else
      flash[:danger] = "編集に失敗しました"
      render :edit
    end

end

private

 def category_params
    params.require(:category).permit(:name, :profile_image, :is_enabled)
 end


end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/edit.html.erb
<div class="row" id="main_background">
<div class="container">
  <div class="row">
       <div class="mx-auto">
<h3 class="font-weight-bold mt-5">Edit Category</h3>
<div class="row">
<p>Category</p>


<%= form_with model: @category, url: categories_path do |category| %>
	<%= category.text_field :name , class: 'ml-5 mt-5 mr-5' %>

	<%=category.submit 'Save', class: 'btn btn-outline-success mb-3 mt-3' %>
<% end %>

   </div>
  </div>
</div>
</div>

app/views/categories/index.html.erb
<div class="row" id="main_background">
  <div class="container">
    <div class="row">
      <div class="col-4 mr-5 border rounded border-info h-50 mb-5 mt-5" id="color">
        <%= render 'post_images/list', post_image: @post_image, user: @user %>
      </div>

    <div class="col-7 mt-5">

					<h3 class="font-weight-bold mr-3 mb-1">Category</h3>
							<%= form_with model: @category,url: categories_path, local: true do |f| %>

 						<%= f.text_field :name, class: 'mb-3 mr-5 ml-3' %>
						<%= f.submit 'Add', class: 'ml-3 mb-3 btn btn-outline-success' %>

						<% end %>



<table class="table table-border mt-1">
	<thead>
		<tr>
			<th>ALL</th>

		</tr>
	</thead>
	<tbody>
		<% current_user.categories.each do |category| %>
			<tr>
				<td><%= category.name %></td>

				<td>
					<%= link_to edit_category_path(category.id), class: 'btn btn-outline-secondary' do %>
						Edit
				</td>
					<% end %>

				<td>
					<%= link_to "Show all", category_path(category.id), class: 'btn btn-secondary' %>
				</td>
			</tr>
		<% end %>
	</tbody>


 </table>
 </div>
 </div>
</div>
</div>
 </div>

app/views/categories/show.html.erb
<div class="row" id="main_background">
<div class="container">
  <div class="row">
   <div class="col-4 border rounded border-info h-50 mb-5 mt-5" id="color">
  <%= render 'post_images/list', post_image: @post_image, user: @user %>
  </div>

<div class="col-8">
  <h3 class="font-weight-bold mr-5 mb-5 ml-5 mt-5">Category:  <%= @category.name %></h3>
    <div class="row">
     <% @post_images.each do |post_image| %>
         <div class="post_group mr-5 mb-5 ml-5">
            <%= link_to post_image_path(post_image.id) do %>
              <div><%= image_tag post_image.image.present? ? post_image.image : "",class: "list_image" %></div>
            <% end %>
          <p>Title:<%= post_image.title %></p>
          <p>Memo:<%= simple_format(post_image.memo) %></p>
          <p>Category：<%= post_image.category.name %></p>
            <div id="star"></div>
              <div id="star-rate<%= post_image.id%>"></div>
            <script>
            $('#star-rate<%= post_image.id%>').raty({
            size      : 36,
            starOff   : '<%= asset_path('star-off.png') %>',
            starOn    : '<%= asset_path('star-on.png') %>',
            half      : false,
            readOnly: true,
            <%# if post_image.review.blank? %>
            //score: 0
            <%# else %>
            //score: <%#= post_image.review %>
            <%# end %>
            score: <%= post_image.review.blank? ? 0 : post_image.review %>
            });
            </script>
         </div>
    <% end %>
    </div>
  </div>

<div class="back center">
<%= link_to "Back", categories_path(@category), class: 'btn btn-secondary mt-5 mb-5' %>
</div>
</div>






</div>