config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'homes/top'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "homes#top"

  resources :post_images, only: [:new, :create, :show, :edit, :index, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :index, :update] do
    resources :relationships, only: [:create, :destroy]
  end
  get "/users/:id/index" => "users#withdraw", as: "withdraw"
  resources :categories, only: [:index, :show, :create, :edit, :update]
  get 'items/search'


end

app/models/post_image.rb
class PostImage < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_one_attached :image
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpeg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpeg', content_type: 'image/jpeg')
    end
    image
  end
  
  def get_profile_image(size)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize: size).processed
  end
 
  
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
end

app/controllers/post_images_controller.rb
class PostImagesController < ApplicationController

  def new
    @post_image = PostImage.new
    @categories = Category.all
    @user = current_user

  end

  def create
    @post_image = PostImage.new(post_image_params)
    @post_image.user_id = current_user.id
    #byebug
    @post_image.save
    redirect_to post_images_path

  end

  def index
    @post_images = PostImage.all
    @user = current_user
    
  end


  def show
    @post_image = PostImage.find(params[:id])
    @post_comment = PostComment.new
    @user = current_user

  end

  def edit
    @post_image = PostImage.find(params[:id])
    @categories = Category.all
    if @post_image.user != current_user
        redirect_to post_image_path
    end


  end

  def update
    @post_image = PostImage.find(params[:id])
    if @post_image.update(post_image_params)
      flash[:notice] ="successfully updated."
    redirect_to post_image_path(@post_image.id)
    else
    render :edit
    end


  end

  def destroy
    @post_image = PostImage.find(params[:id])
    @post_image.destroy
    redirect_to post_images_path
  end

  private

  def post_image_params
    params.require(:post_image).permit(:title, :profile_image, :category_id, :name, :image, :memo, :review)
  end

end

app/helpers/postimages_helper.rb
module PostimagesHelper
end

app/views/post_images/_list.html.erb
<div class = "container">


<h3 class="font-weight-bold"><i class="fas fa-solid fa-house-user text-primary mt-3"></i>  Profile</h3>
<div class="profile-container">

 <%= image_tag @user.get_profile_image("70x70") %>
 <% if @user == current_user %>
 <%= link_to "＋Category", categories_path, class: "btn btn-outline-primary ml-5" %>
  <%= link_to edit_user_path(@user), class: "btn btn-outline-secondary ml-3" do %>
  <i class="fas fa-user-cog"></i> Edit
  <% end %>
  <% end %>



 <table class="table table-hover table-inverse">
 <tbody>
  <tr>
  <th>Name</th><th><div class="profile-name"><%= @user.name %></div></th>
  </tr>
  <tr>
  <th>Age</th><th><div class="age"><%= @user.age %></div></th>
  </tr>
  <th>Gender</th><th><div class="gender"><%= @user.gender %></div></th>
  </tr>
</tbody>
</table>

</div>

    </div>

app/views/post_images/edit.html.erb
<div class="row"  id="main_background">
<div class="container">
  <div class="row">
       <div class="mx-auto">
		  <h3 class="font-weight-bold mt-5">Edit Review</h3>
		  <%= form_with model: @post_image, url: post_image_path(@post_image), method: :patch, local: true do |f| %>
		  <div>

 	  	  <div class="row">
      <h4 class="font-weight-bold ml-5 mr-3 mt-3">Photo:</h4>
        <div class="image mt-3"><%= f.file_field :image, accept: "image/*" %>
        </div></div>
    <div class="row">
      <h4 class="font-weight-bold ml-5 mr-3 mt-3">Title:</h4>
        <div class="title mt-3 ml-3"><%= f.text_field :title %>
        </div></div>
    <div class="row">
      <h4 class="font-weight-bold ml-5 mr-3 mt-3">Memo:</h4>
        <div class="memo mt-3"><%= f.text_area :memo %>
        </div></div>
    <div class="row">
      <h4 class="font-weight-bold ml-5 mr-3 mt-3">Category:</h4>
      <div class="image mt-3"><%= f.collection_select :category_id, @categories, :id, :name, class: 'mb-4' %>
      </div></div>
    <div class="row">
      <h4 class="font-weight-bold ml-5 mr-3 mt-3 mb-3">Review: </h4>
        <div class="form-group mt-3" id="star">
      <%#= f.label :review,'', class:'col-md-1 col-form-label' %>
      <%= f.hidden_field :review, id: :review %>
      </div>
      </div>

    <%= f.submit '投稿', class: 'btn btn-outline-success ml-5 mt-3 mb-5' %>

  <% end %>
   			 <script>
   				 $('#star').raty({
      			 size     : 36,
      			 starOff: '/assets/star-off.png',
      			 starOn : '/assets/star-on.png',
      			 scoreName: 'post_image[review]',
      			 score: <%= @post_image.review %>
    			});
    		</script>

  	</div>
</div>
</div>

app/views/post_images/index.html.erb
 <div class="row" id="main_background">
<div class="container">
  <div class="row">
   <div class="col-4 border rounded border-info h-50 mt-5 mb-5" id="color">
    <%= render 'post_images/list', post_image: @post_image, user: @user %>
   </div>

   <div class="col-8">
<h3 class="font-weight-bold"><i class="fas fa-solid fa-star text-secondary ml-4 mt-5"></i> Reviews</h3>
<div class="row">
<% @post_images.each do |post_image| %>
  <% if post_image.user.blank? %>
    <% next %>
  <% end %>

<div class= "form-group mb-5 mr-3 ml-5 review-group">
<%#= post_image.inspect %>

  <%# if post_image.image.present? %>

     <p><%= link_to user_path(post_image.user) do %>
          <%= image_tag post_image.user.get_profile_image("40x40") %>
        <% end %>
           <%= link_to post_image.user.name, user_path(post_image.user.id) %></p>

     <%= link_to post_image_path(post_image.id) do %>
    <div><%= image_tag post_image.image.present? ? post_image.image : "", class: "list_image mb-1" %></div>
    　<% end %>

  <p>Title：<%= post_image.title %></p>
  <p>Memo：<%= simple_format(post_image.memo) %></p>
  <p>Category：<%= post_image.category.name %></p>
 <div id="star"></div>
    <div id="star-rate<%= post_image.id%>"></div>
    <script>
      $('#star-rate<%= post_image.id%>').raty({
        size      : 36,
        starOff   : '<%= asset_path('star-off.png') %>',
        starOn    : '<%= asset_path('star-on.png') %>',
        half      : false,
        readOnly: true,
        <%# if post_image.review.blank? %>
        //score: 0
        <%# else %>
        //score: <%#= post_image.review %>
        <%# end %>
        score: <%= post_image.review.blank? ? 0 : post_image.review %>
      });
    </script>


   <p><%= post_image.created_at.strftime('%Y/%m/%d') %></p>

</div>
<% end %>
</div>

  </div>
  </div>
</div>

app/views/post_images/new.html.erb
<div class="row" id="main_background">
  <div class="container">
    <div class="row">
      <div class="col-4 border rounded border-info h-50 mt-5" id="color">
        <%= render 'post_images/list', post_image: @post_image, user: @user %>
      </div>

      <div class="col-8 mx-auto new-group">
        <h3 class="font-weight-bold ml-4 mt-5"><i class="fas fa-solid fa-star text-warning"></i> New Post</h3>

        <%= form_with model: @post_image do |f| %>
          <div class="row">
            <h4 class="font-weight-bold text-center ml-5 mr-3 mt-3">Photo:</h4>
              <div class="image mt-3"><%= f.file_field :image, accept: "image/*" %></div>
          </div>
          <div class="row">
            <h4 class="font-weight-bold ml-5 mr-3 mt-3">Title:</h4>
              <div class="title mt-3 ml-3"><%= f.text_field :title %></div>
          </div>
          <div class="row">
            <h4 class="font-weight-bold ml-5 mr-3 mt-3">Memo:</h4>
              <div class="memo mt-3"><%= f.text_area :memo %></div>
          </div>
          <div class="row">
            <h4 class="font-weight-bold ml-5 mr-3 mt-3">Category:</h4>
            <div class="image mt-3"><%= f.collection_select :category_id, @categories, :id, :name, class: 'mb-4' %></div>
          </div>
          <div class="row">
            <h4 class="font-weight-bold ml-5 mr-3 mt-3 mb-3">Review: </h4>
            <div class="form-group mt-3" id="star">
              <%#= f.label :review,'', class:'col-md-1 col-form-label' %>
              <%= f.hidden_field :review, id: :review %>
            </div>
          </div>
          <%= f.submit 'Post', class: 'btn btn-outline-success text-center ml-5 mt-3 mb-5' %>

        <% end %>

          <script>
            $('#star').raty({
              size     : 36,
              starOff: '<%= asset_path('star-off.png') %>',
              starOn : '<%= asset_path('star-on.png') %>',
              scoreName: 'post_image[review]'
            });
          </script>


      </div>
    </div>
  </div>

app/views/post_images/show.html.erb
 <div class="row" id="main_background">
<div class="container">
  <div class="row">
   <div class="col-4 border rounded border-info h-50 mt-5" id="color">
    <%= render 'post_images/list', post_image: @post_image, user: @user %>
   </div>

  <div class="col-3 text-aline ml-5 mr-5 mt-1 mt-5" >
     <p><%= image_tag @post_image.user.get_profile_image("40x40") %>
           <%= link_to @post_image.user.name, user_path(@post_image.user.id) %></p>
    <%= image_tag @post_image.get_image, class: "main_image" %>
      <% if @post_image.user == current_user %>
  <div class="text-center">
    <%= link_to post_image_path(@post_image), method: :delete , "data-confirm" => "本当に消しますか?", class: "btn btn-sm btn-outline-danger mr-3 mt-3" do %>
        Destroy
    <% end %>
    <%= link_to edit_post_image_path(@post_image), class: "btn btn-sm btn-outline-success ml-3 mt-3" do %>
           Edit
    <% end %>
</div>
  <% end %>
    </div>
 <div class="col-3 ml-3 mt-5">
    <h5>Title：<%= @post_image.title %></h5>
    <p>Memo：<%= simple_format(@post_image.memo) %></p>
    <p>Category：<%= @post_image.category.name %></p>
     <div id="star"></div>
    <div id="star-rate<%= @post_image.id%>"></div>
    <script>
      $('#star-rate<%= @post_image.id%>').raty({
        size      : 36,
        starOff   : '<%= asset_path('star-off.png') %>',
        starOn    : '<%= asset_path('star-on.png') %>',
        half      : false,
        readOnly: true,
        <%# if post_image.review.blank? %>
        //score: 0
        <%# else %>
        //score: <%#= post_image.review %>
        <%# end %>
        score: <%= @post_image.review.blank? ? 0 : @post_image.review %>
      });
    </script>



  <p><%= @post_image.created_at.strftime('%Y/%m/%d') %></p>


  <% if @post_image.favorited_by?(current_user) %>
    <p>
      <%= link_to post_image_favorites_path(@post_image), method: :delete do %>
        ♥<%= @post_image.favorites.count %> いいね
      <% end %>
    </p>
    <% else %>
    <p>
      <%= link_to post_image_favorites_path(@post_image), method: :post do %>
        ♡<%= @post_image.favorites.count %> いいね
      <% end %>
    </p>
  <% end %>

  <p>comment：<%= @post_image.post_comments.count %></p>
  <% @post_image.post_comments.each do |post_comment| %>
  <div class="comment">
    <%= post_comment.comment %></div>
    <p><%= image_tag post_comment.user.get_profile_image("50x50") %>
    <%= post_comment.user.name %></p>
    <%= post_comment.created_at.strftime('%Y/%m/%d') %>
  <% end %>


  <%= form_with model: [@post_image, @post_comment] do |f| %>
    <%= f.text_area :comment, rows: '5', placeholder: "コメントをここに" %>
    <%= f.submit "送信する", class: "mb-4" %>
  <% end %>

</div>

</div>
</div>