config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'homes/top'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "homes#top"

  resources :post_images, only: [:new, :create, :show, :edit, :index, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end
  resources :users, only: [:show, :edit, :index, :update] do
    resources :relationships, only: [:create, :destroy]
  end
  get "/users/:id/index" => "users#withdraw", as: "withdraw"
  resources :categories, only: [:index, :show, :create, :edit, :update]
  get 'items/search'


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord

  has_many :post_images, dependent: :destroy
  validates :name, presence: true
  belongs_to :user

  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpeg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpeg', content_type: 'image/jpeg')
    end
    image
  end

  def get_profile_image(size)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize: size).processed
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post_image
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
  belongs_to :user
  belongs_to :post_image
end

app/models/post_image.rb
class PostImage < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_one_attached :image
  has_many :post_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  
  def get_image
    unless image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpeg')
      image.attach(io: File.open(file_path), filename: 'default-image.jpeg', content_type: 'image/jpeg')
    end
    image
  end
  
  def get_profile_image(size)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'no_image.jpg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize: size).processed
  end
 
  
  def favorited_by?(user)
    favorites.exists?(user_id: user.id)
  end
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"


  validates :follower_id, presence: true
  validates :followed_id, presence: true
  validates :follower_id, uniqueness: { scope: :followed_id }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :post_images, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_one_attached :profile_image
  has_many :favorites, dependent: :destroy

  has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :active_relationships, source: :followed

  # フォローされている側のユーザー(passive relationship)
  has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :categories
  enum gender: { man: 0, woman: 1}

  def get_profile_image(size)
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpeg')
      profile_image.attach(io: File.open(file_path), filename: 'no_image.jpeg', content_type: 'image/jpeg')
    end
    profile_image.variant(resize: size).processed
  end

  def age
    today = Date.today # 2014/3/27

    age = today.year - birth_date.year
    if today.month < birth_date.month or (today.month == birth_date.month and today.day < birth_date.day)
      age -= 1 # まだ誕生日を迎えていない
    end

    age
  end

  def follow(other_user)
    active_relationships.create(followed_id: other_user.id)
  end

  # ユーザーをアンフォロー
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # 相手をフォローしていればtrueを返す
  def following?(other_user)
    active_relationships.find_by(followed_id: other_user.id)
  end

  # 友達（互いにフォローしている）をデータベースから取得
  def matchers
    followings & followers
  end

  # 相手と友達になっていればtrueを返す
  def matchers?(other_user)
    active_relationships.find_by(followed_id: other_user.id) && passive_relationships.find_by(follower_id: other_user.id)
  end

  # 自分はフォローしていない&相手からフォローされていればtrueを返す
  def follow_request?(user, other_user)
    !user.matchers?(other_user) && other_user.following?(user)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    post_image = PostImage.find(params[:post_image_id])
    favorite = current_user.favorites.new(post_image_id: post_image.id)
    favorite.save
    redirect_to post_image_path(post_image)
  end

  def destroy
    post_image = PostImage.find(params[:post_image_id])
    favorite = current_user.favorites.find_by(post_image_id: post_image.id)
    favorite.destroy
    redirect_to post_image_path(post_image)
  end
  
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about

  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def search
    @user = current_user
    # @post_images = PostImage.all
    #binding.pry
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @mates = current_user.matchers
    users_id = current_user.followings.pluck(:id)
    pp users_id
    users_id.push(current_user.id)
    pp users_id
    @users = User.where.not(id: users_id)
    @user = current_user
  end

  def show
    @user = User.find(params[:id])
    @post_images = @user.post_images

  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
    if @user.save
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
    render :edit
    end
  end

  def edit
    @user = current_user
    if current_user.id != @user.id
    redirect_to users_path
    end

  end

  def withdraw
    @user = current_user

  end

  def destroy
    user = User.find(params[:id])
    user.update(is_deleted: true)
    flash[:success] = "アカウントを削除しました"
    redirect_to root_path

  end


  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :gender, :birth_date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/postimages_helper.rb
module PostimagesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyReviewRoom</title>
   <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>



  </head>

  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-white bg-white border-bottom border-info">
        <div class="container">
          <a class="navbar-brand p-3" href= / ><%= image_tag('logo.png') %></a>

          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="true" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse collapse show" id="navbarNavDropdown">
            <% if user_signed_in? %>
            <ul class= "navbar-nav ml-auto">

              <%= search_form_for @q, url: items_search_path, class:"search-form" do |f| %>
                <%= f.search_field :title_cont, placeholder: 'キーワードから探す', class:'input-box' %>
                <%= f.button type: "submit", class:"search-button" do %>
                <%= image_tag "search.png", class:"search-icon" %>
                <% end %>
              <% end %>


              <li>
                <%= link_to user_path(current_user.id), class: "nav-link text-dark font-weight-bold" do %>
                <i class="fas fa-home text-success"></i> My room
                <% end %>
              </li>
              <li>
                <%= link_to new_post_image_path, class: "nav-link text-dark font-weight-bold" do %>
                <i class="fas fa-solid fa-star text-warning"></i>New Post
                <% end %>
              </li>
              <li>
                 <%= link_to users_path, class: "nav-link text-dark font-weight-bold" do %>
                 <i class="fas fa-users text-info"></i> Roommate
                 <% end %>
              </li>
              <li>
                <%= link_to post_images_path, class: "nav-link text-dark font-weight-bold" do %>
                <i class="fas fa-solid fa-star text-secondary"></i> Reviews
                <% end %>
              </li>
                <%= link_to destroy_user_session_path, method: :delete, class: "nav-link text-dark font-weight-bold" do %>
                <i class="fas fa-sign-out-alt text-danger"></i> Log out
                <% end %>

            <% else %>

              <%= link_to new_user_registration_path, class: "nav-link text-dark font-weight-bold" do %>
              <i class="fas fa-user-plus text-primary"></i> Sign up
              <% end %>
              <%= link_to new_user_session_path, class: "nav-link text-dark font-weight-bold" do %>
                 <i class="fas fa-sign-in-alt text-success"></i> Log in
              <% end %>
            </ul>
            <% end %>


          </div>
        </div>
      </nav>
    </header>

  <%= yield %>
  </div>



    <main>
       <div class="main_background"></div>
    </main>
    <footer>
      <div class="border-top border-info">
        <div class="row mt-3">
          <div class="mx-auto">
            <p>CopyRight Infratop.inc</p>

          </div>
        </div>
      </div>
    </footer>

 </body>

</html>